---
- name: create user accounts
  hosts: target
  vars_files: vars/userenc.yml
  tasks:
  - name: adding users
    user:
      name: "{{ item.name }}"
      password: "{{ item.pw | password_hash('sha512') }}"
    loop: "{{ newusers}} "
